package Vistas;

import Vistas.jcPanel;

/**
 */
public class VistaHacerTest extends javax.swing.JFrame {

    jcPanel mi_panel = new jcPanel();

    /** Creates new form interfaz */
    public VistaHacerTest(int nRespuestas, String Pregunta) {
        
        
        initComponents();
        labelPregunta.setText(Pregunta);
        //se añade componente al JFrame
        this.add(mi_panel);
        //posicion del panel para no sobreponer al boton
        this.mi_panel.setLocation(10, 50);
         for (int i =0; i<nRespuestas; i++){
         mi_panel.Mi_Componente(this.buttonGroupPreguntas,Integer.toString(i+1)+". Respuestaaaaaaaaaaaaaaaa");
    }
       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPreguntas = new javax.swing.ButtonGroup();
        labelPregunta = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelPregunta.setText("jLabel1");

        btnSiguiente.setText("Siguiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPregunta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaHacerTest(5,"Pregunta:").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup buttonGroupPreguntas;
    public javax.swing.JLabel labelPregunta;
    // End of variables declaration//GEN-END:variables

}
